name: Auto Pull Request

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to monitor

jobs:
  create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (Required for GitHub CLI, adjust if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git checkout -b auto-pr-branch
          git add .
          git commit -m "Automated code changes"
          git push origin auto-pr-branch
          gh pr create --title "Automated Pull Request" --body "This is an automated pull request created by GitHub Actions." --base main --head auto-pr-branch
